env:
  node: true
plugins:
  - prettier
  - eslint-plugin
extends:
  - airbnb-base
  - prettier
  - plugin:eslint-plugin/recommended
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  prettier/prettier: error
  global-require: off
